package cargo_test

// acceptance_test.go verifies the cargo plugin against golden dep graphs
// stored in testdata/acceptance/. Each fixture directory contains a
// Cargo.toml, a Cargo.lock generated by `cargo generate-lockfile`, and an
// expected.json (or expected-<member>.json files for workspaces) capturing
// the full dep graph produced by the plugin.
//
// The test requires cargo in PATH and the per-fixture `.crate` cache to be
// fetchable (run `cargo fetch` inside each fixture dir once before running
// the suite if you don't already have a populated `~/.cargo/registry`).
// Without cargo the suite skips rather than failing — CI may not have it.
//
// Run with `go test -v ./pkg/ecosystems/rust/cargo/... -run TestAcceptance`.
// Use `-update` to overwrite expected.json with the current plugin output.

import (
	"encoding/json"
	"flag"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/snyk/dep-graph/go/pkg/depgraph"

	"github.com/snyk/cli-extension-dep-graph/pkg/ecosystems"
	"github.com/snyk/cli-extension-dep-graph/pkg/ecosystems/rust/cargo"
)

var updateGolden = flag.Bool("update", false, "overwrite expected.json golden files with current plugin output")

type acceptanceFixture struct {
	name string
	dir  string
}

// requireCargo skips the test if cargo is not available in PATH. We do not
// pin a minimum cargo version: `cargo tree --prefix=depth --format='{p}'`
// has been stable since cargo 1.46 (Aug 2020), older than any toolchain
// Snyk customers are likely to run.
func requireCargo(t *testing.T) {
	t.Helper()

	if _, err := exec.LookPath("cargo"); err != nil {
		t.Skip("cargo not found in PATH — skipping acceptance suite (install the Rust toolchain to run these tests)")
	}
}

// TestAcceptance runs the full acceptance suite, comparing plugin output
// against the expected.json in each fixture directory. Skips when cargo is
// absent or when no fixtures have been generated yet.
func TestAcceptance(t *testing.T) {
	requireCargo(t)

	fixtures := discoverFixtures(t, filepath.Join("testdata", "acceptance"))
	if len(fixtures) == 0 {
		t.Skip("no acceptance fixtures yet — see testdata/acceptance/README.md for fixture-generation steps")
	}

	plugin := cargo.Plugin{}

	for _, fx := range fixtures {
		t.Run(fx.name, func(t *testing.T) {
			result, err := plugin.BuildDepGraphsFromDir(t.Context(), nil, fx.dir, &ecosystems.SCAPluginOptions{})
			require.NoError(t, err)
			require.NotEmpty(t, result.Results, "plugin returned no results for fixture %s", fx.name)

			for _, r := range result.Results {
				require.NoError(t, r.Error, "fixture %s produced error result: %v", fx.name, r.Error)
			}

			// Match each result to its golden file by the root package name.
			// Single-crate fixtures use expected.json; workspace fixtures use
			// expected-<rootPkgName>.json so the matching is deterministic.
			byRoot := make(map[string]*depgraph.DepGraph, len(result.Results))
			for _, r := range result.Results {
				byRoot[r.DepGraph.GetRootPkg().Info.Name] = r.DepGraph
			}

			if *updateGolden {
				updateGoldenFiles(t, fx.dir, byRoot)
				return
			}

			compareAgainstGolden(t, fx.dir, byRoot)
		})
	}
}

// discoverFixtures finds all fixture directories under base that have both a
// Cargo.lock and at least one expected*.json. A fixture without an
// expected*.json is treated as not-yet-golden and skipped silently.
func discoverFixtures(t *testing.T, base string) []acceptanceFixture {
	t.Helper()

	entries, err := os.ReadDir(base)
	if err != nil {
		// Base dir may not exist yet — that's fine, just return empty.
		if os.IsNotExist(err) {
			return nil
		}
		require.NoError(t, err, "reading fixtures dir: %s", base)
	}

	var fixtures []acceptanceFixture

	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}

		fxDir := filepath.Join(base, entry.Name())

		if _, err := os.Stat(filepath.Join(fxDir, "Cargo.lock")); err != nil {
			continue
		}

		if !hasGoldenFile(fxDir) {
			continue
		}

		fixtures = append(fixtures, acceptanceFixture{name: entry.Name(), dir: fxDir})
	}

	sort.Slice(fixtures, func(i, j int) bool { return fixtures[i].name < fixtures[j].name })

	return fixtures
}

// hasGoldenFile reports whether dir contains expected.json or any
// expected-*.json file.
func hasGoldenFile(dir string) bool {
	if _, err := os.Stat(filepath.Join(dir, "expected.json")); err == nil {
		return true
	}

	matches, err := filepath.Glob(filepath.Join(dir, "expected-*.json"))
	if err != nil {
		// Only path-syntax errors raise here; treat as "no matches".
		return false
	}
	return len(matches) > 0
}

// goldenFilenameForRoot returns the expected JSON filename for the given
// root package. Single-result fixtures use expected.json; workspace
// fixtures use expected-<rootName>.json.
func goldenFilenameForRoot(dir, rootName string, totalRoots int) string {
	if totalRoots == 1 {
		return filepath.Join(dir, "expected.json")
	}

	return filepath.Join(dir, "expected-"+rootName+".json")
}

func updateGoldenFiles(t *testing.T, dir string, byRoot map[string]*depgraph.DepGraph) {
	t.Helper()

	for rootName, dg := range byRoot {
		path := goldenFilenameForRoot(dir, rootName, len(byRoot))

		// Sort before serializing so committed goldens are stable across
		// regenerations. cargo tree's sibling-emit order isn't fully
		// deterministic (depends on internal hashmap iteration), and Go's
		// map iteration is randomized on top — without sorting, every
		// `go test -update` would produce noisy reorder-only diffs.
		sortDepGraph(dg)

		data, err := json.MarshalIndent(dg, "", "  ")
		require.NoError(t, err, "marshaling dep graph for %s", rootName)

		require.NoError(t, os.WriteFile(path, append(data, '\n'), 0o600), "writing %s", path)
		t.Logf("updated %s", path)
	}
}

func compareAgainstGolden(t *testing.T, dir string, byRoot map[string]*depgraph.DepGraph) {
	t.Helper()

	for rootName, dg := range byRoot {
		path := goldenFilenameForRoot(dir, rootName, len(byRoot))

		raw, err := os.ReadFile(path)
		require.NoError(t, err, "reading %s — run with -update to regenerate", path)

		expected, err := depgraph.UnmarshalJSON(raw)
		require.NoError(t, err, "parsing %s", path)

		assert.Equal(t, normalizedJSON(expected), normalizedJSON(dg), "mismatch in %s", path)
	}
}

// sortDepGraph mutates dg in place to put all arrays into a deterministic
// order: Pkgs by ID, Graph.Nodes by NodeID, each node's Deps by NodeID. Used
// by both the comparison path (normalizedJSON) and the write path
// (updateGoldenFiles) so the same ordering is enforced everywhere.
func sortDepGraph(dg *depgraph.DepGraph) {
	sort.Slice(dg.Pkgs, func(i, j int) bool { return dg.Pkgs[i].ID < dg.Pkgs[j].ID })
	sort.Slice(dg.Graph.Nodes, func(i, j int) bool { return dg.Graph.Nodes[i].NodeID < dg.Graph.Nodes[j].NodeID })

	for i := range dg.Graph.Nodes {
		sort.Slice(dg.Graph.Nodes[i].Deps, func(a, b int) bool {
			return dg.Graph.Nodes[i].Deps[a].NodeID < dg.Graph.Nodes[i].Deps[b].NodeID
		})
	}
}

// normalizedJSON marshals a dep graph to JSON with all arrays sorted so
// comparisons are order-independent. Same pattern as bun's acceptance suite.
func normalizedJSON(dg *depgraph.DepGraph) string {
	sortDepGraph(dg)

	data, err := json.MarshalIndent(dg, "", "  ")
	if err != nil {
		panic(err)
	}

	return string(data)
}
