version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@3.0.0

workflows:
  setup:
    jobs:
      - path-filtering/filter:
          base-revision: main
          mapping: |
            pkg/ecosystems/python/.* run-python-tests true
            pkg/ecosystems/testdata/fixtures/python/.* run-python-tests true
            pkg/ecosystems/gradle/.* run-gradle-tests true
            pkg/ecosystems/testdata/fixtures/gradle/.* run-gradle-tests true
            pkg/ecosystems/javascript/npm/.* run-npm-tests true
            .circleci/.* run-python-tests true
            .circleci/.* run-gradle-tests true
            .circleci/.* run-npm-tests true
          config-path: .circleci/continue-config.yml
