//go:build integration && npm
// +build integration,npm

package npmlocked_test

// plugin_integration_test.go verifies the npm plugin against golden dep
// graphs stored in testdata/acceptance/. Each fixture directory contains a
// package.json, a package-lock.json generated by `npm install --package-lock-only`,
// and an expected.json capturing the dep graph produced by the plugin.
//
// Build tag `integration && npm` keeps these tests out of the default
// `go test ./...` run — they require real npm in PATH.
//
// Run with `make test-npm-integration`, or directly via
//
//	go test -tags=integration,npm -v ./pkg/ecosystems/javascript/npmlocked/...
//
// Regenerate goldens with `-update`.

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"golang.org/x/mod/semver"

	"github.com/snyk/dep-graph/go/pkg/depgraph"

	"github.com/snyk/cli-extension-dep-graph/v2/pkg/ecosystems"
	"github.com/snyk/cli-extension-dep-graph/v2/pkg/ecosystems/javascript/npmlocked"
	"github.com/snyk/cli-extension-dep-graph/v2/pkg/ecosystems/scatest"
)

type acceptanceFixture struct {
	name string
	dir  string
}

var testNpmVersionRe = regexp.MustCompile(`(\d+)\.(\d+)\.(\d+)`)

const minTestNpmVersion = "v6.0.0"

// requireNpm skips the test if npm is absent or older than the minimum
// supported version; fails it if `npm --version` is present but unparseable.
func requireNpm(t *testing.T) {
	t.Helper()
	npmPath, err := exec.LookPath("npm")
	if err != nil {
		t.Skipf("npm not found in PATH — install npm >= %s to run these tests", minTestNpmVersion)
	}
	out, err := exec.Command(npmPath, "--version").Output()
	if err != nil {
		t.Fatalf("failed to get npm version: %v", err)
	}
	raw := strings.TrimSpace(string(out))
	m := testNpmVersionRe.FindStringSubmatch(raw)
	if m == nil {
		t.Fatalf("could not parse npm version from %q", raw)
	}
	ver := "v" + m[1] + "." + m[2] + "." + m[3]
	if semver.Compare(ver, minTestNpmVersion) < 0 {
		t.Skipf("npm %s is below the required minimum %s", ver, minTestNpmVersion)
	}
	t.Logf("npm version: %s", ver)
}

// TestAcceptance runs the acceptance suite for non-workspace fixtures.
func TestAcceptance(t *testing.T) {
	requireNpm(t)

	fixtures := discoverFixtures(t, filepath.Join("testdata", "acceptance"))
	require.NotEmpty(t, fixtures, "no fixtures found")

	plugin := npmlocked.Plugin{}

	for _, fx := range fixtures {
		// Workspace fixtures produce multiple results — covered by TestAcceptance_Workspaces.
		if strings.HasPrefix(fx.name, "workspaces") {
			continue
		}

		t.Run(fx.name, func(t *testing.T) {
			results, err := scatest.Run(context.Background(), plugin, nil, fx.dir, &ecosystems.SCAPluginOptions{})
			require.NoError(t, err)
			require.Len(t, results, 1)
			require.NoError(t, results[0].Error)

			if *updateGolden {
				writeGolden(t, filepath.Join(fx.dir, "expected.json"), results[0].DepGraph)
				return
			}

			raw, err := os.ReadFile(filepath.Join(fx.dir, "expected.json"))
			require.NoError(t, err, "reading expected.json")

			expected, err := depgraph.UnmarshalJSON(raw)
			require.NoError(t, err, "parsing expected.json")

			assert.Equal(t, normalizedJSON(expected), normalizedJSON(results[0].DepGraph))
		})
	}
}

var updateGolden = flag.Bool("update", false, "overwrite expected.json golden files with current plugin output")

// TestAcceptance_Workspaces covers workspace fixtures, which produce one
// dep graph per workspace plus one for the root.
func TestAcceptance_Workspaces(t *testing.T) {
	requireNpm(t)

	type graphCase struct {
		rootPkg string // root package name identifies which result to compare
		golden  string // filename of the golden file inside the fixture dir
	}

	tests := []struct {
		fixture string
		graphs  []graphCase
	}{
		{
			fixture: "workspaces",
			graphs: []graphCase{
				{"npm-workspaces", "expected.json"},
				{"@workspace/logger", "expected-logger.json"},
				{"@workspace/utils", "expected-utils.json"},
			},
		},
	}

	plugin := npmlocked.Plugin{}

	for _, tt := range tests {
		t.Run(tt.fixture, func(t *testing.T) {
			dir := filepath.Join("testdata", "acceptance", tt.fixture)

			results, err := scatest.Run(context.Background(), plugin, nil, dir, &ecosystems.SCAPluginOptions{})
			require.NoError(t, err)
			require.Len(t, results, len(tt.graphs))
			for _, r := range results {
				require.NoError(t, r.Error)
			}

			byRoot := make(map[string]*depgraph.DepGraph, len(results))
			for _, r := range results {
				byRoot[r.DepGraph.GetRootPkg().Info.Name] = r.DepGraph
			}

			if *updateGolden {
				for _, gc := range tt.graphs {
					dg, ok := byRoot[gc.rootPkg]
					require.True(t, ok, "no dep graph with root package %q", gc.rootPkg)
					writeGolden(t, filepath.Join(dir, gc.golden), dg)
				}
				return
			}

			for _, gc := range tt.graphs {
				dg, ok := byRoot[gc.rootPkg]
				require.True(t, ok, "no dep graph with root package %q", gc.rootPkg)

				raw, readErr := os.ReadFile(filepath.Join(dir, gc.golden))
				require.NoError(t, readErr, "reading %s", gc.golden)

				expected, parseErr := depgraph.UnmarshalJSON(raw)
				require.NoError(t, parseErr, "parsing %s", gc.golden)

				assert.Equal(t, normalizedJSON(expected), normalizedJSON(dg), "mismatch in %s", gc.golden)
			}
		})
	}
}

// writeGolden persists a dep graph to the given path as canonical JSON.
func writeGolden(t *testing.T, path string, dg *depgraph.DepGraph) {
	t.Helper()
	data, err := json.MarshalIndent(dg, "", "  ")
	require.NoError(t, err, "marshaling dep graph")
	require.NoError(t, os.WriteFile(path, append(data, '\n'), 0o600), "writing %s", path)
	t.Logf("updated %s", path)
}

// normalizedJSON marshals a dep graph to JSON with all arrays sorted, so
// comparisons are order-independent.
func normalizedJSON(dg *depgraph.DepGraph) string {
	sort.Slice(dg.Pkgs, func(i, j int) bool { return dg.Pkgs[i].ID < dg.Pkgs[j].ID })
	sort.Slice(dg.Graph.Nodes, func(i, j int) bool { return dg.Graph.Nodes[i].NodeID < dg.Graph.Nodes[j].NodeID })

	for i := range dg.Graph.Nodes {
		sort.Slice(dg.Graph.Nodes[i].Deps, func(a, b int) bool {
			return dg.Graph.Nodes[i].Deps[a].NodeID < dg.Graph.Nodes[i].Deps[b].NodeID
		})
	}

	data, err := json.MarshalIndent(dg, "", "  ")
	if err != nil {
		panic(fmt.Errorf("marshaling normalised dep graph: %w", err))
	}
	return string(data)
}

// discoverFixtures finds all fixture dirs with both a package-lock.json and
// (in non-update mode) at least an expected.json. We don't filter on
// expected.json's presence so `-update` can seed brand-new fixtures.
func discoverFixtures(t *testing.T, base string) []acceptanceFixture {
	t.Helper()

	entries, err := os.ReadDir(base)
	require.NoError(t, err, "reading fixtures dir: %s", base)

	var fixtures []acceptanceFixture

	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}

		fxDir := filepath.Join(base, entry.Name())
		if _, err := os.Stat(filepath.Join(fxDir, "package-lock.json")); err != nil {
			continue
		}

		fixtures = append(fixtures, acceptanceFixture{name: entry.Name(), dir: fxDir})
	}

	sort.Slice(fixtures, func(i, j int) bool { return fixtures[i].name < fixtures[j].name })

	return fixtures
}
