package bun_test

// acceptance_test.go verifies the bun plugin against golden dep graphs stored
// in testdata/acceptance/. Each fixture directory contains a package.json, a
// bun.lock generated by `bun install`, and an expected.json capturing the full
// dep graph produced by the plugin.
//
// The test requires bun >= 1.2.19 in PATH and fails otherwise.
// Run with `go test -v ./pkg/ecosystems/javascript/bun/... -run TestAcceptance`.

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"sync"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"golang.org/x/mod/semver"

	"github.com/snyk/dep-graph/go/pkg/depgraph"

	"github.com/snyk/cli-extension-dep-graph/v2/pkg/ecosystems"
	"github.com/snyk/cli-extension-dep-graph/v2/pkg/ecosystems/javascript/bun"
	"github.com/snyk/cli-extension-dep-graph/v2/pkg/ecosystems/logger"
	"github.com/snyk/cli-extension-dep-graph/v2/pkg/ecosystems/scatest"
)

type acceptanceFixture struct {
	name string
	dir  string
}

var testBunVersionRe = regexp.MustCompile(`(\d+)\.(\d+)\.(\d+)`)

// requireBun fails the test immediately if bun is absent from PATH or older
// than v1.2.19, and logs the detected version for CI diagnostics.
func requireBun(t *testing.T) {
	t.Helper()
	bunPath, err := exec.LookPath("bun")
	if err != nil {
		t.Fatal("bun not found in PATH — install bun >= 1.2.19 to run these tests")
	}
	out, err := exec.Command(bunPath, "--version").Output()
	if err != nil {
		t.Fatalf("failed to get bun version: %v", err)
	}
	raw := strings.TrimSpace(string(out))
	m := testBunVersionRe.FindStringSubmatch(raw)
	if m == nil {
		t.Fatalf("could not parse bun version from %q", raw)
	}
	ver := "v" + m[1] + "." + m[2] + "." + m[3]
	if semver.Compare(ver, "v1.2.19") < 0 {
		t.Fatalf("bun %s is below the required minimum v1.2.19", ver)
	}
	t.Logf("bun version: %s", ver)
}

// TestAcceptance runs the full acceptance suite, comparing plugin output against
// the expected.json in each fixture directory.
func TestAcceptance(t *testing.T) {
	runAcceptanceSuite(t, filepath.Join("testdata", "acceptance"), &ecosystems.SCAPluginOptions{})
}

var updateGolden = flag.Bool("update", false, "overwrite expected.json golden files with current plugin output")

// runAcceptanceSuite discovers fixtures under fixtureDir and asserts each one
// produces a dep graph matching its expected.json. Only the first result is
// compared — workspace sub-graphs are covered by TestAcceptance_Workspaces.
func runAcceptanceSuite(t *testing.T, fixtureDir string, opts *ecosystems.SCAPluginOptions) {
	t.Helper()

	requireBun(t)

	fixtures := discoverFixtures(t, fixtureDir)
	require.NotEmpty(t, fixtures, "no fixtures found — check %s", fixtureDir)

	plugin := bun.Plugin{}

	for _, fx := range fixtures {
		if strings.HasPrefix(fx.name, "workspaces") {
			continue // workspace fixtures are covered by TestAcceptance_Workspaces
		}

		t.Run(fx.name, func(t *testing.T) {
			results, err := scatest.Run(t.Context(), plugin, nil, fx.dir, opts)
			require.NoError(t, err)
			require.Len(t, results, 1)
			require.NoError(t, results[0].Error)

			if *updateGolden {
				data, writeErr := json.MarshalIndent(results[0].DepGraph, "", "  ")
				require.NoError(t, writeErr, "marshaling dep graph")
				writeErr = os.WriteFile(filepath.Join(fx.dir, "expected.json"), append(data, '\n'), 0o600)
				require.NoError(t, writeErr, "writing expected.json")
				t.Logf("updated %s/expected.json", fx.name)
				return
			}

			raw, err := os.ReadFile(filepath.Join(fx.dir, "expected.json"))
			require.NoError(t, err, "reading expected.json")

			expected, err := depgraph.UnmarshalJSON(raw)
			require.NoError(t, err, "parsing expected.json")

			assert.Equal(t, normalizedJSON(expected), normalizedJSON(results[0].DepGraph))

			// Every package in bun.lock must appear across all dep graphs.
			// Workspace packages appear in their own dep graph, not the root's.
			allPkgs := allResultPkgs(results)
			assertLockfileCompleteness(t, fx.dir, allPkgs)
		})
	}
}

// TestAcceptance_Workspaces verifies that workspace projects produce one dep
// graph per workspace package plus one for the root, and that each graph
// matches its named golden file.
func TestAcceptance_Workspaces(t *testing.T) {
	requireBun(t)

	type graphCase struct {
		rootPkg string // root package name identifies which result to compare
		golden  string // filename of the golden file inside the fixture dir
	}

	tests := []struct {
		fixture string
		graphs  []graphCase
	}{
		{
			fixture: "workspaces",
			graphs: []graphCase{
				{"bun-workspaces", "expected.json"},
				{"a", "expected-a.json"},
				{"b", "expected-b.json"},
			},
		},
		{
			fixture: "workspaces-cross-dep",
			graphs: []graphCase{
				{"my-monorepo", "expected.json"},
				{"a", "expected-a.json"},
				{"b", "expected-b.json"},
			},
		},
		{
			fixture: "workspaces-glob-a",
			graphs: []graphCase{
				{"bun-workspaces", "expected.json"},
				{"a", "expected-a.json"},
				{"b", "expected-b.json"},
			},
		},
		{
			fixture: "workspaces-glob-b",
			graphs: []graphCase{
				{"bun-workspaces", "expected.json"},
				{"a", "expected-a.json"},
				{"b", "expected-b.json"},
			},
		},
		{
			fixture: "workspaces-packages",
			graphs: []graphCase{
				{"bun-workspaces", "expected.json"},
				{"a", "expected-a.json"},
				{"b", "expected-b.json"},
			},
		},
		{
			fixture: "workspaces-catalog",
			graphs: []graphCase{
				{"my-catalog-monorepo", "expected.json"},
				{"a", "expected-a.json"},
				{"b", "expected-b.json"},
			},
		},
	}

	plugin := bun.Plugin{}

	for _, tt := range tests {
		t.Run(tt.fixture, func(t *testing.T) {
			dir := filepath.Join("testdata", "acceptance", tt.fixture)

			results, err := scatest.Run(t.Context(), plugin, nil, dir, &ecosystems.SCAPluginOptions{})
			require.NoError(t, err)
			require.Greater(t, len(results), 1)
			require.Len(t, results, len(tt.graphs))

			for _, r := range results {
				require.NoError(t, r.Error)
			}

			// Index results by root package name for golden-file lookup.
			byRoot := make(map[string]*depgraph.DepGraph, len(results))
			for _, r := range results {
				byRoot[r.DepGraph.GetRootPkg().Info.Name] = r.DepGraph
			}

			if *updateGolden {
				for _, gc := range tt.graphs {
					dg, ok := byRoot[gc.rootPkg]
					require.True(t, ok, "no dep graph with root package %q", gc.rootPkg)

					data, writeErr := json.MarshalIndent(dg, "", "  ")
					require.NoError(t, writeErr, "marshaling dep graph for %s", gc.golden)
					writeErr = os.WriteFile(filepath.Join(dir, gc.golden), append(data, '\n'), 0o600)
					require.NoError(t, writeErr, "writing %s", gc.golden)
					t.Logf("updated %s/%s", tt.fixture, gc.golden)
				}

				assertLockfileCompleteness(t, dir, allResultPkgs(results))
				return
			}

			for _, gc := range tt.graphs {
				dg, ok := byRoot[gc.rootPkg]
				require.True(t, ok, "no dep graph with root package %q", gc.rootPkg)

				raw, readErr := os.ReadFile(filepath.Join(dir, gc.golden))
				require.NoError(t, readErr, "reading %s", gc.golden)

				expected, parseErr := depgraph.UnmarshalJSON(raw)
				require.NoError(t, parseErr, "parsing %s", gc.golden)

				assert.Equal(t, normalizedJSON(expected), normalizedJSON(dg), "mismatch in %s", gc.golden)
			}

			assertLockfileCompleteness(t, dir, allResultPkgs(results))
		})
	}
}

// TestInvalidPackageJSON verifies that a directory where bun install failed
// (due to malformed package.json) produces no results rather than a crash.
// There is intentionally no bun.lock in this fixture — that's the scenario
// being tested.
func TestInvalidPackageJSON(t *testing.T) {
	plugin := bun.Plugin{}
	opts := &ecosystems.SCAPluginOptions{}

	dir := filepath.Join("testdata", "acceptance", "invalid-pkg-json")

	results, err := scatest.Run(t.Context(), plugin, nil, dir, opts)
	require.NoError(t, err)
	assert.Empty(t, results)
}

// assertLockfileCompleteness verifies that every package resolved in bun.lock
// appears in pkgs. It parses the bun.lock JSONC, extracts all resolved IDs
// from the packages section, and fails the test for any that are absent.
//
// bun.lock versions using the "file:" protocol are normalised to strip the
// prefix (bun why omits it), so "@scope/pkg@file:../x" matches "@scope/pkg@../x".
func assertLockfileCompleteness(t *testing.T, dir string, pkgs []depgraph.Pkg) {
	t.Helper()

	for _, id := range lockfilePackagesMissingFromGraph(t, dir, pkgs) {
		t.Errorf("bun.lock package %q is missing from the dep graph", id)
	}
}

// lockfilePackagesMissingFromGraph returns the IDs of packages present in
// bun.lock but absent from pkgs. Unlike assertLockfileCompleteness it does
// not call t.Fail, so callers can decide how to handle the result.
func lockfilePackagesMissingFromGraph(t *testing.T, dir string, pkgs []depgraph.Pkg) []string {
	t.Helper()

	data, err := os.ReadFile(filepath.Join(dir, "bun.lock"))
	require.NoError(t, err, "reading bun.lock")

	// bun.lock is JSONC — strip trailing commas before parsing.
	cleaned := bunLockTrailingCommaRe.ReplaceAll(data, []byte("$1"))

	var lock struct {
		Packages map[string][]json.RawMessage `json:"packages"`
	}
	require.NoError(t, json.Unmarshal(cleaned, &lock), "parsing bun.lock")

	graphIDs := make(map[string]struct{}, len(pkgs))
	for _, p := range pkgs {
		graphIDs[p.ID] = struct{}{}
	}

	var missing []string

	for _, entry := range lock.Packages {
		if len(entry) == 0 {
			continue
		}

		var id string
		if err := json.Unmarshal(entry[0], &id); err != nil {
			t.Errorf("lockfilePackagesMissingFromGraph: failed to parse package entry %s: %v — bun.lock format may have changed", entry[0], err)
			continue
		}

		// Normalise "file:" protocol in versions to match bun why output.
		id = stripFileProtocol(id)

		if _, ok := graphIDs[id]; !ok {
			missing = append(missing, id)
		}
	}

	return missing
}

// TestBundledDepsVisibleInBunWhy verifies that packages bundled inside another
// package's distribution appear in the dep graph produced by the plugin.
//
// This is a known bun bug (https://github.com/oven-sh/bun/issues/29263):
// `bun why '*' --top` outputs "No dependents found" for bundled packages,
// making them invisible to the plugin. The test is marked expected-to-fail
// via t.Skip while the bug persists. When a bun release fixes it the test
// will pass automatically — at that point remove the t.Skipf call below
// and close the tracking issue.
func TestBundledDepsVisibleInBunWhy(t *testing.T) {
	requireBun(t)

	plugin := bun.Plugin{}
	dir := filepath.Join("testdata", "bundled-deps")

	results, err := scatest.Run(t.Context(), plugin, nil, dir, &ecosystems.SCAPluginOptions{})
	require.NoError(t, err)
	require.Len(t, results, 1)
	require.NoError(t, results[0].Error)

	missing := lockfilePackagesMissingFromGraph(t, dir, allResultPkgs(results))
	if len(missing) == 0 {
		// bun has fixed the bug — remove the t.Skipf below and close the issue.
		return
	}

	t.Skipf(
		"known bun bug #29263 — %d bundled package(s) not reported by `bun why '*' --top`: %v\n"+
			"track at https://github.com/oven-sh/bun/issues/29263",
		len(missing), missing,
	)
}

// allResultPkgs aggregates Pkgs from all SCAResults into a single flat slice.
// Used to check lockfile completeness across a workspace project's multiple dep graphs.
func allResultPkgs(results []ecosystems.SCAResult) []depgraph.Pkg {
	var all []depgraph.Pkg
	for _, r := range results {
		if r.DepGraph != nil {
			all = append(all, r.DepGraph.Pkgs...)
		}
	}
	return all
}

var bunLockTrailingCommaRe = regexp.MustCompile(`,(\s*[}\]])`)

// stripFileProtocol converts "@scope/pkg@file:../path" to "@scope/pkg@../path"
// to match the ID format bun why produces.
func stripFileProtocol(id string) string {
	i := strings.LastIndex(id, "@")
	if i <= 0 {
		return id
	}

	if strings.HasPrefix(id[i+1:], "file:") {
		return id[:i+1] + id[i+1+len("file:"):]
	}

	return id
}

// normalizedJSON marshals a dep graph to JSON with all arrays sorted, so
// comparisons are order-independent.
func normalizedJSON(dg *depgraph.DepGraph) string {
	sort.Slice(dg.Pkgs, func(i, j int) bool { return dg.Pkgs[i].ID < dg.Pkgs[j].ID })
	sort.Slice(dg.Graph.Nodes, func(i, j int) bool { return dg.Graph.Nodes[i].NodeID < dg.Graph.Nodes[j].NodeID })

	for i := range dg.Graph.Nodes {
		sort.Slice(dg.Graph.Nodes[i].Deps, func(a, b int) bool {
			return dg.Graph.Nodes[i].Deps[a].NodeID < dg.Graph.Nodes[i].Deps[b].NodeID
		})
	}

	data, err := json.MarshalIndent(dg, "", "  ")
	if err != nil {
		panic(err)
	}

	return string(data)
}

// TestAcceptanceNoUnrecognizedLines verifies that real `bun why '*' --top`
// output never hits the parser's default (skip) branch. A line falling through
// to that branch means a regex gap that silently drops dependency information.
func TestAcceptanceNoUnrecognizedLines(t *testing.T) {
	requireBun(t)

	plugin := bun.Plugin{}

	for _, fx := range discoverFixtures(t, filepath.Join("testdata", "acceptance")) {
		t.Run(fx.name, func(t *testing.T) {
			log := &recordingLogger{}
			_, err := scatest.Run(t.Context(), plugin, log, fx.dir, &ecosystems.SCAPluginOptions{})
			require.NoError(t, err)
			log.assertNoUnrecognizedLines(t)
		})
	}
}

// recordingLogger captures "Skipping unrecognized" debug messages from the
// bun why parser so tests can assert none were emitted.
type recordingLogger struct {
	mu      sync.Mutex
	skipped []string
}

func (r *recordingLogger) Info(_ context.Context, _ string, _ ...logger.Field)  {}
func (r *recordingLogger) Error(_ context.Context, _ string, _ ...logger.Field) {}

func (r *recordingLogger) Debug(_ context.Context, msg string, fields ...logger.Field) {
	if msg != "Skipping unrecognized bun why output line" {
		return
	}
	r.mu.Lock()
	defer r.mu.Unlock()
	for _, f := range fields {
		if f.Key == "line" {
			r.skipped = append(r.skipped, fmt.Sprint(f.Value))
		}
	}
}

func (r *recordingLogger) assertNoUnrecognizedLines(t *testing.T) {
	t.Helper()
	r.mu.Lock()
	defer r.mu.Unlock()
	for _, line := range r.skipped {
		t.Errorf("unrecognized bun why line: %q", line)
	}
}

// discoverFixtures finds all fixture directories under base that have both a
// bun.lock and an expected.json.
func discoverFixtures(t *testing.T, base string) []acceptanceFixture {
	t.Helper()

	entries, err := os.ReadDir(base)
	require.NoError(t, err, "reading fixtures dir: %s", base)

	var fixtures []acceptanceFixture

	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}

		fxDir := filepath.Join(base, entry.Name())

		if _, err := os.Stat(filepath.Join(fxDir, "bun.lock")); err != nil {
			continue
		}

		if _, err := os.Stat(filepath.Join(fxDir, "expected.json")); err != nil {
			continue
		}

		fixtures = append(fixtures, acceptanceFixture{name: entry.Name(), dir: fxDir})
	}

	sort.Slice(fixtures, func(i, j int) bool { return fixtures[i].name < fixtures[j].name })

	return fixtures
}
