package bun_test

// acceptance_test.go verifies the bun plugin against golden dep graphs stored
// in testdata/acceptance/. Each fixture directory contains a package.json, a
// bun.lock generated by `bun install`, and an expected.json capturing the full
// dep graph produced by the plugin.
//
// The test requires bun >= 1.2.19 in PATH and is skipped otherwise.
// Run with `go test -v ./pkg/ecosystems/javascript/bun/... -run TestAcceptance`.

import (
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/snyk/cli-extension-dep-graph/pkg/ecosystems"
	"github.com/snyk/cli-extension-dep-graph/pkg/ecosystems/javascript/bun"
	"github.com/snyk/dep-graph/go/pkg/depgraph"
)

type acceptanceFixture struct {
	name string
	dir  string
}

// TestAcceptance runs the full acceptance suite, comparing plugin output against
// the expected.json in each fixture directory.
func TestAcceptance(t *testing.T) {
	if _, err := exec.LookPath("bun"); err != nil {
		t.Skip("bun not found in PATH — skipping acceptance suite")
	}

	fixtures := discoverFixtures(t, filepath.Join("testdata", "acceptance"))
	require.NotEmpty(t, fixtures, "no acceptance fixtures found — check testdata/acceptance/")

	plugin := bun.Plugin{}
	opts := &ecosystems.SCAPluginOptions{}

	for _, fx := range fixtures {
		t.Run(fx.name, func(t *testing.T) {
			result, err := plugin.BuildDepGraphsFromDir(t.Context(), nil, fx.dir, opts)
			require.NoError(t, err)
			require.NotEmpty(t, result.Results)
			require.NoError(t, result.Results[0].Error)

			raw, err := os.ReadFile(filepath.Join(fx.dir, "expected.json"))
			require.NoError(t, err, "reading expected.json")

			expected, err := depgraph.UnmarshalJSON(raw)
			require.NoError(t, err, "parsing expected.json")

			assert.Equal(t, normalizedJSON(expected), normalizedJSON(result.Results[0].DepGraph))
		})
	}
}

// TestAcceptanceDev runs the acceptance suite with dev dependencies included,
// comparing plugin output against the expected.json in testdata/acceptance_dev/.
func TestAcceptanceDev(t *testing.T) {
	if _, err := exec.LookPath("bun"); err != nil {
		t.Skip("bun not found in PATH — skipping acceptance suite")
	}

	fixtures := discoverFixtures(t, filepath.Join("testdata", "acceptance_dev"))
	require.NotEmpty(t, fixtures, "no acceptance_dev fixtures found — check testdata/acceptance_dev/")

	plugin := bun.Plugin{}
	opts := &ecosystems.SCAPluginOptions{
		Global: ecosystems.GlobalOptions{
			IncludeDev: true,
		},
	}

	for _, fx := range fixtures {
		t.Run(fx.name, func(t *testing.T) {
			result, err := plugin.BuildDepGraphsFromDir(t.Context(), nil, fx.dir, opts)
			require.NoError(t, err)
			require.NotEmpty(t, result.Results)
			require.NoError(t, result.Results[0].Error)

			raw, err := os.ReadFile(filepath.Join(fx.dir, "expected.json"))
			require.NoError(t, err, "reading expected.json")

			expected, err := depgraph.UnmarshalJSON(raw)
			require.NoError(t, err, "parsing expected.json")

			assert.Equal(t, normalizedJSON(expected), normalizedJSON(result.Results[0].DepGraph))
		})
	}
}

// TestInvalidPackageJSON verifies that a directory where bun install failed
// (due to malformed package.json) produces no results rather than a crash.
// There is intentionally no bun.lock in this fixture — that's the scenario
// being tested.
func TestInvalidPackageJSON(t *testing.T) {
	plugin := bun.Plugin{}
	opts := &ecosystems.SCAPluginOptions{}

	dir := filepath.Join("testdata", "depgraphs", "invalid-pkg-json")

	result, err := plugin.BuildDepGraphsFromDir(t.Context(), nil, dir, opts)
	require.NoError(t, err)
	assert.Empty(t, result.Results)
}

// normalizedJSON marshals a dep graph to JSON with all arrays sorted, so
// comparisons are order-independent.
func normalizedJSON(dg *depgraph.DepGraph) string {
	sort.Slice(dg.Pkgs, func(i, j int) bool { return dg.Pkgs[i].ID < dg.Pkgs[j].ID })
	sort.Slice(dg.Graph.Nodes, func(i, j int) bool { return dg.Graph.Nodes[i].NodeID < dg.Graph.Nodes[j].NodeID })

	for i := range dg.Graph.Nodes {
		sort.Slice(dg.Graph.Nodes[i].Deps, func(a, b int) bool {
			return dg.Graph.Nodes[i].Deps[a].NodeID < dg.Graph.Nodes[i].Deps[b].NodeID
		})
	}

	data, err := json.MarshalIndent(dg, "", "  ")
	if err != nil {
		panic(err)
	}

	return string(data)
}

// discoverFixtures finds all fixture directories under base that have both a
// bun.lock and an expected.json.
func discoverFixtures(t *testing.T, base string) []acceptanceFixture {
	t.Helper()

	entries, err := os.ReadDir(base)
	require.NoError(t, err, "reading fixtures dir: %s", base)

	var fixtures []acceptanceFixture

	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}

		fxDir := filepath.Join(base, entry.Name())

		if _, err := os.Stat(filepath.Join(fxDir, "bun.lock")); err != nil {
			continue
		}

		if _, err := os.Stat(filepath.Join(fxDir, "expected.json")); err != nil {
			continue
		}

		fixtures = append(fixtures, acceptanceFixture{name: entry.Name(), dir: fxDir})
	}

	sort.Slice(fixtures, func(i, j int) bool { return fixtures[i].name < fixtures[j].name })

	return fixtures
}
