//go:build integration && composer
// +build integration,composer

package composer_test

// plugin_integration_test.go verifies the composer plugin against golden
// dep graphs stored in testdata/acceptance/. Each fixture directory
// contains a composer.json, a composer.lock generated by real composer
// (or hand-rolled to match composer's lockfile format), and an
// expected.json capturing the dep graph produced by the plugin.
//
// Build tag `integration && composer` keeps these tests out of the
// default `go test ./...` run — they require real composer 2.x in PATH.
//
// Run with `make test-composer-integration`, or directly via
//
//	go test -tags=integration,composer -v \
//	  ./pkg/ecosystems/php/composer/...
//
// Regenerate goldens with `-update`.
//
// Acceptance contract: after the plugin runs against a fixture, the
// fixture directory must contain no `vendor/` and no `composer.lock.bak`
// — the plugin is offline-only and must not mutate the project tree.

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"golang.org/x/mod/semver"

	"github.com/snyk/dep-graph/go/pkg/depgraph"

	"github.com/snyk/cli-extension-dep-graph/v2/pkg/ecosystems"
	"github.com/snyk/cli-extension-dep-graph/v2/pkg/ecosystems/php/composer"
	"github.com/snyk/cli-extension-dep-graph/v2/pkg/ecosystems/scatest"
)

type acceptanceFixture struct {
	name string
	dir  string
}

var testComposerVersionRe = regexp.MustCompile(`(\d+)\.(\d+)\.(\d+)`)

const minTestComposerVersion = "v2.0.0"

// requireComposer skips the test if composer is absent or older than the
// minimum supported version; fails it if `composer --version` is present
// but unparseable.
func requireComposer(t *testing.T) {
	t.Helper()
	composerPath, err := exec.LookPath("composer")
	if err != nil {
		t.Skipf("composer not found in PATH — install composer >= %s to run these tests", minTestComposerVersion)
	}
	out, err := exec.Command(composerPath, "--version", "--no-ansi").Output()
	if err != nil {
		t.Fatalf("failed to get composer version: %v", err)
	}
	raw := strings.TrimSpace(string(out))
	m := testComposerVersionRe.FindStringSubmatch(raw)
	if m == nil {
		t.Fatalf("could not parse composer version from %q", raw)
	}
	ver := "v" + m[1] + "." + m[2] + "." + m[3]
	if semver.Compare(ver, minTestComposerVersion) < 0 {
		t.Skipf("composer %s is below the required minimum %s", ver, minTestComposerVersion)
	}
	t.Logf("composer version: %s", ver)
}

var updateGolden = flag.Bool("update", false, "overwrite expected.json golden files with current plugin output")

// TestAcceptance runs the acceptance suite against every fixture and
// asserts the resulting dep graph matches the stored expected.json.
func TestAcceptance(t *testing.T) {
	requireComposer(t)

	fixtures := discoverFixtures(t, filepath.Join("testdata", "acceptance"))
	require.NotEmpty(t, fixtures, "no fixtures found")

	plugin := composer.Plugin{}

	for _, fx := range fixtures {
		t.Run(fx.name, func(t *testing.T) {
			results, err := scatest.Run(context.Background(), plugin, nil, fx.dir, &ecosystems.SCAPluginOptions{})
			require.NoError(t, err)
			require.Len(t, results, 1)
			require.NoError(t, results[0].Error)

			// Offline contract: composer show --locked must not create
			// vendor/ or any other install artifact in the fixture dir.
			assertNoInstallArtifacts(t, fx.dir)

			if *updateGolden {
				writeGolden(t, filepath.Join(fx.dir, "expected.json"), results[0].DepGraph)
				return
			}

			raw, err := os.ReadFile(filepath.Join(fx.dir, "expected.json"))
			require.NoError(t, err, "reading expected.json")

			expected, err := depgraph.UnmarshalJSON(raw)
			require.NoError(t, err, "parsing expected.json")

			assert.Equal(t, normalizedJSON(expected), normalizedJSON(results[0].DepGraph))
		})
	}
}

// assertNoInstallArtifacts is the teeth of principle #2 (offline +
// install-free). After running the plugin, the fixture directory must
// not contain vendor/, composer.lock.bak, or any other install footprint.
//
// Mirrors PR 204's `simple/` acceptance assertion that no node_modules/
// is created.
func assertNoInstallArtifacts(t *testing.T, dir string) {
	t.Helper()
	forbidden := []string{"vendor", "composer.lock.bak"}
	for _, name := range forbidden {
		_, err := os.Stat(filepath.Join(dir, name))
		assert.True(t, os.IsNotExist(err),
			"%s must not be created by the resolver (got err: %v)", name, err)
	}
}

// writeGolden persists a dep graph to the given path as canonical JSON.
func writeGolden(t *testing.T, path string, dg *depgraph.DepGraph) {
	t.Helper()
	data, err := json.MarshalIndent(dg, "", "  ")
	require.NoError(t, err, "marshaling dep graph")
	require.NoError(t, os.WriteFile(path, append(data, '\n'), 0o600), "writing %s", path)
	t.Logf("updated %s", path)
}

// normalizedJSON marshals a dep graph to JSON with all arrays sorted,
// so comparisons are order-independent (composer plugin sorts children
// lexicographically but pkgs[] ordering depends on insertion order).
func normalizedJSON(dg *depgraph.DepGraph) string {
	sort.Slice(dg.Pkgs, func(i, j int) bool { return dg.Pkgs[i].ID < dg.Pkgs[j].ID })
	sort.Slice(dg.Graph.Nodes, func(i, j int) bool { return dg.Graph.Nodes[i].NodeID < dg.Graph.Nodes[j].NodeID })

	for i := range dg.Graph.Nodes {
		sort.Slice(dg.Graph.Nodes[i].Deps, func(a, b int) bool {
			return dg.Graph.Nodes[i].Deps[a].NodeID < dg.Graph.Nodes[i].Deps[b].NodeID
		})
	}

	data, err := json.MarshalIndent(dg, "", "  ")
	if err != nil {
		panic(fmt.Errorf("marshaling normalised dep graph: %w", err))
	}
	return string(data)
}

// discoverFixtures finds all fixture dirs with a composer.lock. We don't
// filter on expected.json's presence so `-update` can seed brand-new
// fixtures.
func discoverFixtures(t *testing.T, base string) []acceptanceFixture {
	t.Helper()

	entries, err := os.ReadDir(base)
	require.NoError(t, err, "reading fixtures dir: %s", base)

	var fixtures []acceptanceFixture

	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}

		fxDir := filepath.Join(base, entry.Name())
		if _, err := os.Stat(filepath.Join(fxDir, "composer.lock")); err != nil {
			continue
		}

		fixtures = append(fixtures, acceptanceFixture{name: entry.Name(), dir: fxDir})
	}

	sort.Slice(fixtures, func(i, j int) bool { return fixtures[i].name < fixtures[j].name })

	return fixtures
}
